### ISSUE TITLE
newbie pains

### ISSUE THREAD

**Issue by bentxt** [SvenMichaelKlose/tre#2]
Hi 
I try to get started with tre and have some starter pains with the examples:

1. when compiling stuff like 'examples/make-standard-node.lisp', I get a .js file, but it actually a html file in the sense it contains valid html, that cannot be run with node. Any way if I delete the html tags, it is still not running

```
$> ./tre examples/make-standard-node.lisp
$> node compiled/hello-world.js
$> hello-world.js:26745
    a1 = AVAILABLELANGUAGES;
    ^
ReferenceError: AVAILABLELANGUAGES is not defined
```

2. Then when I try to run a standard js example this is not working neither:

```
./tre examples/make-standard-js.lisp

$> open -a Chrome compiled/hello-world.html

# in the js dev console
hello-world.html:6666 Uncaught ReferenceError: process is not defined
    at tre_getenv (hello-world.html:6666:5)
    at hello-world.html:10447:10
```

Tre looks cool and I'd like to get to know it better, maybe you can help with this

Thanks Ben

**Comment by SvenMichaelKlose** [comment]
Thanks for your report and your interest in tré!

I'll gladly fix the bugs. Sadly, the support for Node hasn't been taken care of for several web epochs, so you'll end up with a construction site anyway, effectively adding to tré itself. Of course that'd be awesome. 8) I'm lacking a bit of experience with Node development.

Best regards,
Sven
