### ISSUE TITLE
JS target not working

### ISSUE THREAD

**Issue by bentxt** [SvenMichaelKlose/tre#7]
Hi Sven,

I already hinted that I have problems with Javascript, so I hope you don't mind I make a dedicated issue here.

Info: I removed the docker stuff in make.sh 

```
cd examples/project-js
sh ./make.sh
cd compiled
php -S localhost:19020
```

When I visit that address I get the following error in the console:

```
Uncaught ReferenceError: process is not defined
    at tre_getenv ((index):6666:5)
    at (index):10450:10
```

**Comment by bentxt** [comment]
There seems to be node stuff in line 6666, but even I delete the line and then handle the subsequent errors the same way I never get that sweet "Hello World" ;-(

**Comment by SvenMichaelKlose** [comment]
Thanks! Fixed on 'master', but that revealed https://github.com/SvenMichaelKlose/tre/issues/9, so that's next.
